# Frases motivacionales y reflexiones para la bio del perfil
# Ampliado con más variedad y categorías

quotes_teletips = [
    # Original
    "Love For All, Hatred For None.",
    "Change the world by being yourself.",
    "Every moment is a fresh beginning.",
    "Never regret anything that made you smile.",
    "Die with memories, not dreams.",
    "Aspire to inspire before we expire.",
    "Everything you can imagine is real.",
    "Simplicity is the ultimate sophistication.",
    "Whatever you do, do it well.",
    "What we think, we become.",
    "All limitations are self-imposed.",
    "Tough times never last but tough people do.",
    "Problems are not stop signs, they are guidelines.",
    "Have enough courage to start and enough heart to finish.",
    "I could agree with you but then we'd both be wrong.",
    "Oh, the things you can find, if you don't stay behind.",
    "Determine your priorities and focus on them.",
    "Be so good they can't ignore you.",
    "Yesterday you said tomorrow. Just do it.",
    "I don't need it to be easy, I need it to be worth it.",
    "Never let your emotions overpower your intelligence.",
    "Nothing lasts forever but at least we got these memories.",
    "Don't you know your imperfections is a blessing?",
    "Reality is wrong, dreams are for real.",
    "To live will be an awfully big adventure.",
    "Try to be a rainbow in someone's cloud.",
    "There is no substitute for hard work.",
    "What consumes your mind controls your life.",
    "Strive for greatness.",
    "And still, I rise.",
    "The time is always right to do what is right.",
    "Let the beauty of what you love be what you do.",
    "May your choices reflect your hopes, not your fears.",
    "A happy soul is the best shield for a cruel world.",
    "White is not always light and black is not always dark.",
    "Happiness depends upon ourselves.",
    "Turn your wounds into wisdom.",
    "Change the game, don't let the game change you.",
    "It hurt because it mattered.",
    "I will remember and recover, not forgive and forget.",
    "The meaning of life is to give life meaning.",
    "When words fail, music speaks.",
    "Embrace the glorious mess that you are.",
    "I have nothing to lose but something to gain.",
    # Nuevas frases
    "Be the energy you want to attract.",
    "Stars can't shine without darkness.",
    "In a world full of trends, remain a classic.",
    "Your vibe attracts your tribe.",
    "Less perfection, more authenticity.",
    "The best is yet to come.",
    "Create the things you wish existed.",
    "Progress, not perfection.",
    "Stay close to people who feel like sunshine.",
    "You are allowed to be both a masterpiece and a work in progress.",
    "Don't wait for opportunity, create it.",
    "Life is short, make it sweet.",
    "Be a voice, not an echo.",
    "Collect moments, not things.",
    "Do what is right, not what is easy.",
    "Fall seven times, stand up eight.",
    "The only impossible journey is the one you never begin.",
    "Dream big, work hard, stay focused.",
    "Make each day your masterpiece.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Breathe. It's just a bad day, not a bad life.",
    "She believed she could, so she did.",
    "Not all who wander are lost.",
    "Keep going. Everything you need will come at the right time.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Inhale courage, exhale fear.",
    "You were born to be real, not to be perfect.",
    "Difficult roads often lead to beautiful destinations.",
    "Everything will be okay in the end. If it's not okay, it's not the end.",
    "Work hard in silence, let your success be the noise.",
    "A smooth sea never made a skilled sailor.",
    "Don't compare your beginning to someone else's middle.",
    "Life begins at the end of your comfort zone.",
    "Small steps every day lead to big changes.",
    "Mindset is everything.",
    "Be patient with yourself. Growth takes time.",
    "Your potential is endless.",
    "Choose kindness and laugh often.",
    "Stay positive, work hard, make it happen.",
]
